# Generated by Django 4.1.3 on 2022-11-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
