# Generated by Django 4.1.3 on 2022-11-14 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_order_alter_cart_owner_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
